export const projects = [
  {
    id: 9,
    name: "🍔 Space burgers",
    description:
      "Burger constructor. Fullstack MERN. React, Redux, JWT Auth, DnD.",
    year: 2023,
    featured: true,
    designOnly: false,
    demoURL: "https://space-burgers.netlify.app/",
    codeURL: "https://github.com/arbuznik/react-burger",
  },
  {
    id: 8,
    name: "🎯 How to focus",
    description:
      "Responsive one-page about what to do when you can't concentrate.",
    year: 2023,
    featured: false,
    designOnly: true,
    demoURL: "https://arbuznik-focus.netlify.app/",
    codeURL: "https://github.com/arbuznik/focus",
  },
  {
    id: 7,
    name: "💳 Eshop payment",
    description:
      "Responsive payment screen with smart card form. Nunjucks, Gulp, SCSS.",
    year: 2023,
    featured: false,
    designOnly: true,
    demoURL: "https://arbuznik-eshop-payment.netlify.app/",
    codeURL: "https://github.com/arbuznik/sborka-payment",
  },
  {
    id: 6,
    name: "📊 Array sorting",
    description: "Visualizations of array sorting algorithms.",
    year: 2023,
    featured: true,
    demoURL: "https://arbuznik-array-sorting.netlify.app/",
    codeURL: "https://github.com/arbuznik/a-sort",
  },
  {
    id: 5,
    name: "🍉 Arbuznik.com",
    description:
      "This blog is built with Gatsby on top of *.md vault managed with Obsidian.",
    year: 2023,
    featured: true,
    codeURL: "https://github.com/arbuznik/arbuznik.com",
  },
  {
    id: 4,
    name: "👨‍💻 Hacker News",
    description:
      "Hacker News reader app. Peculiar API, tree traversal and recursive components.",
    year: 2022,
    featured: true,
    demoURL: "https://arbuznik-hacker-news.netlify.app/",
    articleURL: "/projects/hacker-news/",
    codeURL: "https://github.com/arbuznik/hacker-news",
  },
  {
    id: 3,
    name: "📚 Bookshelf",
    description:
      "Browse through vast books catalog. Built on top of Google books API.",
    year: 2022,
    featured: true,
    demoURL: "https://arbuznik-bookshelf.netlify.app/",
    codeURL: "https://github.com/arbuznik/bookshelf",
  },
  {
    id: 2,
    name: "🎬 Movie explorer",
    description:
      "Fullstack MERN app. Browse movies and save them into your personal account. You will have to register first.",
    year: 2022,
    featured: true,
    demoURL: "https://arbuznik-movie-explorer.netlify.app/",
    articleURL: "/projects/movie-explorer/",
    codeURL: "https://github.com/arbuznik/movies-explorer-frontend",
    codeBackendURL: "https://github.com/arbuznik/movies-explorer-api",
  },
  {
    id: 1,
    name: "🦹 Know your name",
    description:
      "Make assumptions on person given the name. Consolidated data from different sources.",
    year: 2021,
    featured: true,
    demoURL: "https://arbuznik.github.io/know-your-name/",
    articleURL: "/projects/know-your-name/",
    codeURL: "https://github.com/arbuznik/know-your-name",
  },
  {
    id: 0,
    name: "🐮 Bulls and Cows",
    description: "Classic game of numbers.",
    year: 2021,
    featured: true,
    demoURL: "https://arbuznik.github.io/bulls-and-cows/",
    articleURL: "/projects/bulls-and-cows/",
    codeURL: "https://github.com/arbuznik/bulls-and-cows",
  },
];
